### ISSUE TITLE
{{fn (mut foo)}} throws an error

### ISSUE THREAD

**Issue by elwayman02** [rwjblue/ember-fn-helper-polyfill#36]
When doing `@bar={{fn (mut foo)}}`, the following error gets thrown:

> You must pass a function as the `fn` helpers first argument, you passed false

This appears to work in Ember 3.11+, where the polyfill is inert, but it does not work with the polyfill. As such, this seems to be a deviation in behavior between the polyfill and the actual implementation.

**Comment by rwjblue** [comment]
Ya, we can make this work. Should also ensure that `{{fn (action foo)}}` works.

**Comment by elwayman02** [comment]
For reference, here's the non-polyfill implementation in later Ember versions: https://github.com/emberjs/ember.js/blob/v3.18.1/packages/%40ember/-internals/glimmer/lib/helpers/fn.ts

**Comment by elwayman02** [comment]
Closing - The issue here was having the polyfill as a devDep instead of a dep - the transform wasn't running properly

**Comment by rwjblue** [comment]
I’m still going to snag those tests you wrote. They seem good to have around regardless.
