### ISSUE TITLE
Not working correctly with `mut`

### ISSUE THREAD

**Issue by balinterdi** [rwjblue/ember-fn-helper-polyfill#6]
I'm using the `fn` helper as below to handle events on an input:

```
<input
  type="text"
  value={{@band.name}}
  {{on "blur" (fn (mut showErrors.name) true)}}
  {{on "input" (fn this.updateName @band)}}
>
```

The `input` handler works perfectly but I get the following error for the `blur` one:

> Assertion Failed: You must pass a function as the `fn` helpers first argument, you passed false

**Comment by lifeart** [comment]
Looks like `mut` not working without `action`

**Comment by balinterdi** [comment]
Right, but if you have `action`, you don't need `mut`. At any rate, Rob confirmed this is a bug and asked me to create this issue so that we can track it.

**Comment by rwjblue** [comment]
Submitted https://github.com/rwjblue/ember-fn-helper-polyfill/pull/7 to fix.

**Comment by rwjblue** [comment]
Released in https://github.com/rwjblue/ember-fn-helper-polyfill/releases/tag/v1.0.1
